import type { Metadata } from "next";
import { Fira_Code, Montserrat, Bentham} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-providers";

const montserrat = Montserrat({
  variable: "--montserrat",
  subsets: ["latin"],
});

const bentham = Bentham({
  variable: "--bentham",
  weight: ["400"]
})

const firaCode = Fira_Code({
  variable: "--fira-code",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montserrat.variable} ${firaCode.variable} ${bentham.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
